overviews/csde_ratspoda3.txt
overviews/csde_ratspoda3.bmp
maps/csde_ratspoda3.res
maps/csde_ratspoda3.txt
sound/csde_ratspoda3/musique.wav
models/csde_ratspoda3/coca.mdl
models/csde_ratspoda3/jambon.mdl
models/csde_ratspoda3/poulet.mdl
models/csde_ratspoda3/pepsi.mdl